### ISSUE TITLE
CDN Library Version invalid chars

### ISSUE THREAD

**Issue by bthibault** [keen/keen-dataviz.js#76]
this is breaking my stuff

https://d26b395fwzu5fz.cloudfront.net/keen-dataviz-1.1.3.js

line 9714 :   var Îµ = 1e-6, Îµ2 = Îµ * Îµ, Ï€ = Math.PI, Ï„ = 2 * Ï€, Ï„Îµ = Ï„ - Îµ, halfÏ€ = Ï€ / 2, d3_radians = Ï€ / 180, d3_degrees = 180 / Ï€;

Not sure if this actually working for anybody ?

**Comment by dustinlarimer** [comment]
@bthibault this issue is caused by special characters in D3.js source: https://github.com/d3/d3/issues/1195#issuecomment-16262373

You can get around this by including a meta tag that sets document encoding to UTF-8:

```html
<!DOCTYPE html>
<meta charset="utf-8">
```

Or set it on the script tag that includes this library:

```html
<script charset="utf-8" src="keen-dataviz.js"></script>
```

Apologies for the bumpy ride! I updated our docs recently to emphasize this, but it may need to be made a bit more prominent. Please let me know if you have any issues with this fix!

**Comment by dustinlarimer** [comment]
Leaving this open as a point of reference for anyone else hitting this issue.

Another workaround here is to just use the minified version, as described in https://github.com/d3/d3/issues/1195#issuecomment-16262373.

**Comment by dustinlarimer** [comment]
@bthibault I've updated the Content-Type for v1.2.0.. this should work as expected now: https://d26b395fwzu5fz.cloudfront.net/keen-dataviz-1.2.0.js

Please let me know if you continue having issues with this!

**Comment by dustinlarimer** [comment]
FYI: This should now be fixed for all versions in our CDN.
