### ISSUE TITLE
D3 not available when RequireJS is present

### ISSUE THREAD

**Issue by alejandromagnorsky** [keen/keen-dataviz.js#86]
When I call chart.render() for piechart it throws the following error:

```
keen.js:19724 Unhandled rejection TypeError: d3.select is not a function
    at Dataviz.module.exports (http://localhost:8010/lib/keen.js:23456:25)
    at Dataviz.render (http://localhost:8010/lib/keen.js:24074:40)
    at http://localhost:8010/lib/keen.js:23264:55
    at domReady (http://localhost:8010/lib/keen.js:23361:13)
    at Dataviz.render (http://localhost:8010/lib/keen.js:23242:9)
```

Using version 4.3.0 of keen-js.
Furthermore the legend is not showing in any chart type.

**Comment by dustinlarimer** [comment]
@alejandromagnorsky can you please share a bit of your setup code here, plus any other dependencies you may have included in the page?

**Comment by dustinlarimer** [comment]
Legends appear to be working correctly on my end, so I suspect there may be an environmental issue at play.

<img width="416" alt="screen shot 2017-10-10 at 4 13 42 pm" src="https://user-images.githubusercontent.com/180438/31415086-03a46bac-add6-11e7-896d-7c9085a30327.png">

**Comment by alejandromagnorsky** [comment]
@dustinlarimer, yes. Here is an example with the pie chart:
https://codepen.io/alejandrocsb/pen/gGKPmz
If you check the console you can see the error: **id.substring is not a function**
Not sure why it's different from the one I got in my complex application. But regardless, there is an error. 
Also, I made another pen to check about the labels and I was able to see them, so that's fine.

Thanks.

**Comment by alejandromagnorsky** [comment]
After some more debugging I discovered that Keen v4.3.0 works perfect in my application if I load it with the <script> tag instead of using requirejs. Basically, it looks like requirejs is breaking it slightly.

**Comment by dustinlarimer** [comment]
Thank your for digging into that further and helping figuring this out!

Require has issues with nested dependencies that also define Require modules. I just double-checked the version of D3 we're including, and it's module definition block looks like this:

```javascript
// ...
if (typeof define === "function" && define.amd) this.d3 = d3, define(d3); else if (typeof module === "object" && module.exports) module.exports = d3; else this.d3 = d3;
```

If I'm reading this correctly, when RequireJS is present the D3 module just isn't loaded the way our library expects to reference it.. which in turn triggers the `d3.select is not a function` error you noted. I'll look into solutions for patching this up.. Sorry for the bumpy ride!

---

As for the original issue, I think this `id.substring()` error stems from an edge case with the type of data being passed in. Categorical data labels are passed in as a string, but in this case those labels are likely `Date` instances, since your query uses an interval but no groups.

Example:
```javascript
new Date().substring(0, 10);
> Uncaught TypeError: (intermediate value).substring is not a function
```

Try changing the `type` to `'line'` or `'area'` and it should work as expected. I'll look into the error and see if type-enforcement can squash the issue.

**Comment by adamkasprowicz** [comment]
Hi @alejandromagnorsky ,

We've just published new versions of our 3 core libs.
* https://github.com/keen/keen-analysis.js
* https://github.com/keen/keen-dataviz.js
* https://github.com/keen/keen-tracking.js

Moving from keen-js main package to standalone packages will give you much more freedom and new opportunities. Especially if you are using js bundlers.

Thanks
